try {
  var x = y + 1;
} catch (err) {
  console.log('error!')
} finally {
  console.log('done!')
}